"""Add nullable true to comment

Revision ID: f430ff5a4160
Revises: 366a6fa49471
Create Date: 2022-01-12 13:06:56.502453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f430ff5a4160'
down_revision = '366a6fa49471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
                    existing_type=sa.TEXT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
                    existing_type=sa.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###
