"""empty message

Revision ID: 02cb3af8635a
Revises: f2ba3c1c0e6f
Create Date: 2022-01-11 16:45:17.721807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cb3af8635a'
down_revision = 'f2ba3c1c0e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_to_items', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories_to_items', 'id')
    # ### end Alembic commands ###
